### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by gdedi001** [ce-real/teacozy#1]
_Grade: Satisfactory_

Good job on your project - you met some of the design requirements to a tee and your code looks very detailed! In addition to this, you utilized the `<div>` tag properly, thus creating a much needed sense of organization for a project that calls for such an approach. An area for improvement here is with the positioning of your content. 

A recommendation here is to play the following game that teaches flexbox. Try applying the concepts and its usage. It will aid you as your projects get more complex. Read it thoroughly and view the examples! Keep it up!

**Comment by ce-real** [comment]
Thank you so much for the helpful and thorough feedback on this project.  I also really appreciate the recommendation of Flexbox Froggy - it was a great way to break down Flexbox into a more focused way to understand it.  I definitely think it helped me as I used Flexbox in subsequent projects.  Thanks again!
